service: bref2-bench-fpm

provider:
    name: aws
    region: us-east-2
    runtime: provided.al2

plugins:
    - ./vendor/bref/bref

functions:
    128:
        handler: index.php
        memorySize: 128
        layers:
            - ${bref:layer.php-81-fpm}
        events:
            -   httpApi: 'GET /128'
    512:
        handler: index.php
        memorySize: 512
        layers:
            - ${bref:layer.php-81-fpm}
        events:
            -   httpApi: 'GET /512'
    1024:
        handler: index.php
        memorySize: 1024
        layers:
            - ${bref:layer.php-81-fpm}
        events:
            -   httpApi: 'GET /1024'
    1769:
        handler: index.php
        memorySize: 1769
        layers:
            - ${bref:layer.php-81-fpm}
        events:
            -   httpApi: 'GET /1769'

    128-arm:
        handler: index.php
        memorySize: 128
        architecture: arm64
        layers:
            - ${bref:layer.arm-php-80-fpm}
        events:
            -   httpApi: 'GET /128-arm'
    512-arm:
        handler: index.php
        memorySize: 512
        architecture: arm64
        layers:
            - ${bref:layer.arm-php-80-fpm}
        events:
            -   httpApi: 'GET /512-arm'
    1024-arm:
        handler: index.php
        memorySize: 1024
        architecture: arm64
        layers:
            - ${bref:layer.arm-php-80-fpm}
        events:
            -   httpApi: 'GET /1024-arm'
    1769-arm:
        handler: index.php
        memorySize: 1769
        architecture: arm64
        layers:
            - ${bref:layer.arm-php-80-fpm}
        events:
            -   httpApi: 'GET /1769-arm'
