service: bref2-bench-fpm

provider:
    name: aws
    region: us-east-2
    runtime: provided.al2
    layers:
        - ${bref:layer.php-81-fpm}

plugins:
    - ./vendor/bref/bref

functions:
    128:
        handler: index.php
        memorySize: 128
        events:
            -   httpApi: 'GET /128'
    512:
        handler: index.php
        memorySize: 512
        events:
            -   httpApi: 'GET /512'
    1024:
        handler: index.php
        memorySize: 1024
        events:
            -   httpApi: 'GET /1024'
    1769:
        handler: index.php
        memorySize: 1769
        events:
            -   httpApi: 'GET /1769'
